hist(lm3$residuals, main="Residual distribution")
shapiro.test(lm3$residuals)
plot(lm3$residuals~lm3$fitted.values,main="Model diagnosis")
abline(lm(lm3$residuals~lm3$fitted.values),col="red")
summary(lm(pm1$residuals~pm1$fitted.values))
AIC(lm3,pm1)
plot(Richness~NAP,data=RIKZ, pch=19)
library(ciTools)
ci_pm1<-add_ci(RIKZ, pm1, alpha = 0.05, names = c("lwr", "upr"))
lines(ci_pm1$NAP, ci_pm1$pred, col = "red", lwd = 1,lty="solid")
lines(ci_pm1$NAP, ci_pm1$upr, col = "red", lwd = 1,lty="dotted")
lines(ci_pm1$NAP, ci_pm1$lwr, col = "red", lwd = 1,lty="dotted")
title("glm-poisson regression")
library(nlme)
rr<-read.csv("rrplantsoil.csv",header = TRUE)
fix(rr)
rr1<-lme(rrno3~N*Nadd,random = ~1|Block/Year,data = rr)##两个随机因子
summary(rr1)
rr<-read.csv("mydataB2.csv",header = TRUE)
fix(rr)
rr1<-lme(pd~N*Nadd*Pre,random = ~1|Block,data = rr)##一个随机因子
summary(rr1)
